---
deployment:
  tasks:
    - export REPOPATH=/home/simb9878/repositories/simonev-sop
    - export DEPLOYPATH=/home/simb9878/public_html
    - echo "🚀 Deployment started at $(date)" >> /home/simb9878/deploy.log
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -r $REPOPATH/public/* $DEPLOYPATH/
    - /bin/sed -i "s#../vendor/#../repositories/simonev-sop/vendor/#g" $DEPLOYPATH/index.php
    - /bin/sed -i "s#../bootstrap/#../repositories/simonev-sop/bootstrap/#g" $DEPLOYPATH/index.php
    - echo "✅ Deployment finished at $(date)" >> /home/simb9878/deploy.log
