---
deployment:
  tasks:
    - export DEPLOYPATH=/home/simb9878/public_html
    - echo "🚀 Deployment started at $(date)" >> /home/simb9878/deploy.log
    - /bin/cp -r $(ls -A | grep -v '^public_html$') $DEPLOYPATH >> /home/simb9878/deploy.log 2>&1
    - echo "✅ Deployment finished at $(date)" >> /home/simb9878/deploy.log
